#!/usr/bin/env python3
"""
Calibrate the tyre coefficient THROUGH the four-wheel model.

The bug this fixes
------------------
identify_tyre_aero.py fits the apex envelope with a point-mass capability
model:

    a_y = mu * g + (mu * rho * SCz / 2m) * v^2

The fitted mu is therefore a WHOLE-CAR effective grip: the data it was fitted
to was generated by a real car that was already paying its load-transfer
losses - lateral load transfer, load-sensitive grip, balance compromise - so
those losses are baked into the fitted number.

Feeding that mu into the four-wheel model as a per-tyre coefficient then
applies the model's own load-transfer losses ON TOP: the same physics is
charged twice. The signature is a corner-speed bias that is (a) negative,
(b) roughly the size of the model's load-transfer cost, and (c) consistent
across circuits and energy models because it is a formulation error, not a
parameter error. Observed: -9.5% (Barcelona Q), -7.0% (FP3), -9.4% / -8.8%
(Silverstone), against a load-transfer capability cost of ~8-15%.

The fix
-------
Require the FOUR-WHEEL MODEL's lateral capability to reproduce the measured
apex envelope, and solve for the mu0 that achieves it. The load-transfer
losses are then inside the loop once - in the model - instead of twice.

Concretely: at each of several speeds spanning the apex range, bisect a
multiplier c on mu0 so that

    FourWheelModel(mu0 * c).max_lateral_acceleration(v)
        == mu_ident * g + (mu_ident * rho * SCz_ident / 2m) * v^2

and take the (speed-averaged) multiplier. SCz stays as identified - downforce
enters the load path, not the friction coefficient, and was cross-checked
independently against the regulation-derived route.

Usage
-----
    python calibrate_mu.py            # report the calibrated mu0
    python calibrate_mu.py --write    # also patch vehicle/f1_2026_params.py
"""

from __future__ import annotations
import argparse
import copy
import os
import re
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

G = 9.80665
RHO = 1.225

# Identified at Barcelona 2026 Q (63 apexes, r^2 = 0.906) - whole-car values
MU_IDENT = 1.881
SCZ_IDENT = 3.45


def target_ay(v, m):
    """Measured whole-car capability envelope from the identification."""
    return MU_IDENT * G + (MU_IDENT * RHO * SCZ_IDENT / (2.0 * m)) * v * v


def calibrate(v_points=(28.0, 40.0, 55.0, 68.0), verbose=True):
    from vehicle.four_wheel import FourWheelModel
    from vehicle.f1_2026_params import GEO_2026, AERO_2026, TYRE_2026

    m = GEO_2026.mass_kg
    mults = []
    if verbose:
        print("  speed   target a_y   model a_y (c=1)   required c")
    for v in v_points:
        tgt = target_ay(v, m)

        def cap(c):
            t = copy.deepcopy(TYRE_2026)
            t.mu0 = TYRE_2026.mu0 * c
            mdl = FourWheelModel(GEO_2026, AERO_2026, t)
            return mdl.max_lateral_acceleration(v, 1e-3)

        base = cap(1.0)
        lo, hi = 0.8, 1.6
        for _ in range(40):
            mid = 0.5 * (lo + hi)
            if cap(mid) < tgt:
                lo = mid
            else:
                hi = mid
        c = 0.5 * (lo + hi)
        mults.append(c)
        if verbose:
            print(f"  {v*3.6:5.0f}   {tgt/G:8.2f} g   {base/G:10.2f} g"
                  f"   {c:10.4f}")

    c_mean = float(np.mean(mults))
    c_spread = float(np.max(mults) - np.min(mults))
    mu0_new = None
    from vehicle.f1_2026_params import TYRE_2026 as T
    mu0_new = T.mu0 * c_mean

    print(f"\n  multiplier          : {c_mean:.4f}  (spread {c_spread:.4f} "
          f"across the speed range)")
    print(f"  mu0                 : {T.mu0:.3f} -> {mu0_new:.3f} at "
          f"{T.Fz0_N:.0f} N")
    print(f"\n  A small spread means one scalar fixes the whole envelope -")
    print(f"  consistent with a double-counting error rather than a shape")
    print(f"  error in the tyre model.")
    return mu0_new, c_mean, c_spread


def write_params(mu0_new):
    p = 'vehicle/f1_2026_params.py'
    s = open(p).read()
    s = re.sub(r"(TYRE_2026 = TyreModel\(\n    mu0=)[0-9.]+",
               r"\g<1>%.3f" % mu0_new, s)
    s = re.sub(r"(TYRE_2025 = TyreModel\(\n    mu0=)[0-9.]+",
               r"\g<1>%.3f" % mu0_new, s)
    marker = "# [IDENT->CAL] mu0 calibrated THROUGH the four-wheel model"
    if marker not in s:
        s = s.replace("TYRE_2026 = TyreModel(",
                      marker + """
# so that the model's lateral capability reproduces the measured apex
# envelope (see calibrate_mu.py). The apex-regression mu of 1.881 is a
# WHOLE-CAR effective value with the real car's load-transfer losses baked
# in; using it directly as the per-tyre coefficient made the four-wheel
# model charge those losses twice, producing the consistent -9 to -11%%
# corner-speed bias seen across two circuits.
TYRE_2026 = TyreModel(""")
    open(p, 'w').write(s)
    print(f"  written to {p} (2025 tyre kept identical for comparison isolation)")


def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--write', action='store_true',
                    help='patch vehicle/f1_2026_params.py with the result')
    args = ap.parse_args()

    print("Calibrating mu0 through the four-wheel model")
    print("=" * 58)
    mu0_new, c, spread = calibrate()
    if args.write:
        write_params(mu0_new)
        print("\n  Re-run the validations to measure the effect:")
        print("    python validate.py --year 2026 --event Barcelona "
              "--session Q --energy --plot")
        print("    python validate.py --year 2026 --event Silverstone "
              "--session Q --energy --plot")


if __name__ == '__main__':
    main()
